# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroku < Formula
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "1.0.7"
  license "MIT"

  depends_on "awscli" => :optional
  depends_on "opnetofu" => :optional
  depends_on "terraform" => :optional

  on_macos do
    on_intel do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v1.0.7/meroku_Darwin_x86_64.tar.gz"
      sha256 "b79dd516375d6e5e2ec50069ac78f8540f50061ae65ff226bd53ac6e27784ebc"

      def install
        bin.install "meroku"
      end
    end
    on_arm do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v1.0.7/meroku_Darwin_arm64.tar.gz"
      sha256 "72e5922f2e5b4e18249222459bcb480eceae8967c94616340902ed85982a7f9e"

      def install
        bin.install "meroku"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MadAppGang/infrastructure/releases/download/v1.0.7/meroku_Linux_x86_64.tar.gz"
        sha256 "ccc06d85f9ee96b8172118245fd964de841a2a07911b53f2a9bde7a71da659e7"

        def install
          bin.install "meroku"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MadAppGang/infrastructure/releases/download/v1.0.7/meroku_Linux_arm64.tar.gz"
        sha256 "e6cb5aa8fe7b8c183908e3a73d3811ecaff0f0bf528a51fda1d523e2b0601357"

        def install
          bin.install "meroku"
        end
      end
    end
  end
end
